mutation AddProduct(
  $description: String!
  $imageUrl: String!
  $name: String!
  $price: Float!
) @auth(level: PUBLIC) {
  product_insert(
    data: {
      description: $description
      imageUrl: $imageUrl
      name: $name
      price: $price
    }
  )
}

mutation AddProductField(
  $productId: UUID!
  $order: Int!
  $attributes: Any
  $expectedData: [String!]
  $handler: String!
  $fieldName: String!
) @auth(level: PUBLIC) {
  productField_insert(
    data: {
      productId: $productId
      order: $order
      attributes: $attributes
      expectedData: $expectedData
      handler: $handler
      fieldName: $fieldName
    }
  )
}

mutation DeleteProductField($id: UUID!) @auth(level: PUBLIC) {
  productField_delete(key: { id: $id })
}
