mutation AddProduct(
  $id: UUID
  $description: String!
  $imageUrl: String!
  $name: String!
  $currencies: String!
) @auth(level: PUBLIC) {
  product_insert(
    data: {
      id: $id
      description: $description
      imageUrl: $imageUrl
      name: $name
      currencies: $currencies
    }
  )
}

mutation DeleteProduct($id: UUID!) @auth(level: PUBLIC) {
  product_delete(key: { id: $id })
}

mutation AddProductField(
  $productId: UUID!
  $order: Int!
  $priceImages: Any
  $expectedData: [String!]
  $handler: String!
  $fieldName: String!
  $isPriceImage: Boolean!
) @auth(level: PUBLIC) {
  productField_insert(
    data: {
      productId: $productId
      order: $order
      priceImages: $priceImages
      expectedData: $expectedData
      handler: $handler
      fieldName: $fieldName
      isPriceImage: $isPriceImage
    }
  )
}

mutation DeleteProductField($id: UUID!) @auth(level: PUBLIC) {
  productField_delete(key: { id: $id })
}

mutation AddCurrencies(
  $name: String!
  $mainCurrency: String!
  $rub: Float!
  $usd: Float!
) @auth(level: PUBLIC) {
  currencies_insert(
    data: { name: $name, mainCurrency: $mainCurrency, rub: $rub, usd: $usd }
  )
}

mutation DeleteCurrencies($id: UUID!) @auth(level: PUBLIC) {
  currencies_delete(key: { id: $id })
}

mutation UpdateProduct(
  $id: UUID!
  $name: String!
  $description: String!
  $imageUrl: String!
  $currencies: String!
) @auth(level: PUBLIC) {
  product_update(
    id: $id
    data: {
      name: $name
      description: $description
      imageUrl: $imageUrl
      currencies: $currencies
    }
  )
}

mutation productFieldUpdate(
  $id: UUID
  $productId: UUID!
  $order: Int!
  $priceImages: Any
  $expectedData: [String!]
  $handler: String!
  $fieldName: String!
  $isPriceImage: Boolean!
) @auth(level: PUBLIC) {
  productField_update(
    id: $id
    data: {
      productId: $productId
      order: $order
      priceImages: $priceImages
      expectedData: $expectedData
      handler: $handler
      fieldName: $fieldName
      isPriceImage: $isPriceImage
    }
  )
}

mutation currenciesUpdate(
  $id: UUID!
  $name: String!
  $mainCurrency: String!
  $rub: Float!
  $usd: Float!
) @auth(level: PUBLIC) {
  currencies_update(
    id: $id
    data: { name: $name, mainCurrency: $mainCurrency, rub: $rub, usd: $usd }
  )
}
