mutation AddProduct(
  $id: UUID
  $description: String!
  $imageUrl: String!
  $name: String!
  $currencies: String!
) @auth(level: PUBLIC) {
  product_insert(
    data: {
      id: $id
      description: $description
      imageUrl: $imageUrl
      name: $name
      currencies: $currencies
    }
  )
}

mutation DeleteProduct($id: UUID!) @auth(level: PUBLIC) {
  product_delete(key: { id: $id })
}

mutation UpdateProduct(
  $id: UUID!
  $name: String
  $description: String
  $imageUrl: String
  $currencies: String
) @auth(level: PUBLIC) {
  product_update(
    key: { id: $id }
    data: {
      name: $name
      description: $description
      imageUrl: $imageUrl
      currencies: $currencies
    }
  )
}

mutation AddProductField(
  $productId: UUID!
  $order: Int!
  $priceImages: Any
  $expectedData: [String!]
  $handler: String!
  $fieldName: String!
  $isPriceImage: Boolean!
) @auth(level: PUBLIC) {
  productField_insert(
    data: {
      productId: $productId
      order: $order
      priceImages: $priceImages
      expectedData: $expectedData
      handler: $handler
      fieldName: $fieldName
      isPriceImage: $isPriceImage
    }
  )
}

mutation DeleteProductField($id: UUID!) @auth(level: PUBLIC) {
  productField_delete(key: { id: $id })
}

mutation AddCurrencies(
  $name: String!
  $mainCurrency: String!
  $rub: Float!
  $usd: Float!
) @auth(level: PUBLIC) {
  currencies_insert(
    data: { name: $name, mainCurrency: $mainCurrency, rub: $rub, usd: $usd }
  )
}

mutation DeleteCurrencies($id: UUID!) @auth(level: PUBLIC) {
  currencies_delete(key: { id: $id })
}

mutation productFieldUpdate(
  $id: UUID
  $productId: UUID!
  $order: Int!
  $priceImages: Any
  $expectedData: [String!]
  $handler: String!
  $fieldName: String!
  $isPriceImage: Boolean!
) @auth(level: PUBLIC) {
  productField_update(
    id: $id
    data: {
      productId: $productId
      order: $order
      priceImages: $priceImages
      expectedData: $expectedData
      handler: $handler
      fieldName: $fieldName
      isPriceImage: $isPriceImage
    }
  )
}

mutation currenciesUpdate(
  $id: UUID!
  $name: String!
  $mainCurrency: String!
  $rub: Float!
  $usd: Float!
) @auth(level: PUBLIC) {
  currencies_update(
    id: $id
    data: { name: $name, mainCurrency: $mainCurrency, rub: $rub, usd: $usd }
  )
}

mutation deleteCartItem($id: UUID!) @auth(level: PUBLIC) {
  cartItem_delete(key: { id: $id })
}

mutation addCartItem(
  $id: UUID
  $userId: String!
  $userName: String!
  $productId: UUID!
  $productName: String!
  $purchaseData: Any!
  $currency: String!
  $checkoutPrice: Float!
  $status: String!
  $comment: String
) @auth(level: PUBLIC) {
  cartItem_insert(
    data: {
      id: $id
      userId: $userId
      userName: $userName
      productId: $productId
      productName: $productName
      purchaseData: $purchaseData
      currency: $currency
      checkoutPrice: $checkoutPrice
      status: $status
      comment: $comment
    }
  )
}

mutation UpdateCartItem(
  $id: UUID!
  $userId: String
  $userName: String
  # $productId: UUID,
  # $productName: String,
  # $purchaseData: Any,
  # $currency: String,
  # $checkoutPrice: Float,
  $status: String
  $comment: String
  $statusChangedAt: Timestamp
) @auth(level: PUBLIC) {
  cartItem_update(
    key: { id: $id }
    data: {
      userId: $userId
      userName: $userName
      # productId: $productId,
      # productName: $productName,
      # purchaseData: $purchaseData,
      # currency: $currency,
      # checkoutPrice: $checkoutPrice,
      status: $status
      comment: $comment
      statusChangedAt: $statusChangedAt
    }
  )
}

mutation DeleteLastAddedProductCartItem($userId: String!, $productId: UUID!)
@auth(level: PUBLIC) {
  _execute(
    sql: """
    DELETE FROM cart_item
    WHERE id = (
      SELECT id
      FROM cart_item
      WHERE user_id = $1 AND product_id = $2
      ORDER BY created_at DESC
      LIMIT 1
    )
    """
    params: [$userId, $productId]
  )
}
