query GetAllProductsQuery @auth(level: PUBLIC) {
  products {
    id
    name
    description
    price
    imageUrl
  }
}

query GetProductFieldsQuery($productId: UUID!) @auth(level: PUBLIC) {
  productFields(where: { productId: { eq: $productId } }) {
    productId
    id
    order
    fieldName
    handler
    attributes
    expectedData
  }
}
