query GetAllProductsQuery @auth(level: PUBLIC) {
  products {
    id
    name
    description
    imageUrl
    currencies
  }
}

query GetProductFieldsQuery($productId: UUID!) @auth(level: PUBLIC) {
  productFields(where: { productId: { eq: $productId } }) {
    productId
    id
    order
    fieldName
    isPriceImage
    handler
    priceImages
    expectedData
  }
}


query GetAllCurrenciesQuery @auth(level: PUBLIC) {
  currenciess {
    id
    name
    mainCurrency
    rub
    usd
  }
}
