subscription streamUsersCartItems($userId: String) {
  cartItems_subscribe(where: { userId: { eq: $userId } }) {
    id
    userId
    userName
    productId
    productName
    purchaseData
    currency
    checkoutPrice
    createdAt
    status
    comment
    statusChangedAt
  }
}
