extend type ProductProperties {
  """
  ✨ Implicit foreign key field based on `ProductProperties`.`product`. It must match the value of `Product`.`id`. See `@ref` for how to customize it.
  """
  productId: UUID! @fdc_generated(from: "ProductProperties.product", purpose: IMPLICIT_REF_FIELD)
}
