extend type Mutation {
  """
  ✨ Insert a single `Currencies` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  currencies_insert(
    """
    Data object to insert into the table.
    """
    data: Currencies_Data!
  ): Currencies_KeyOutput! @fdc_generated(from: "Currencies", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PriceFunction` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  priceFunction_insert(
    """
    Data object to insert into the table.
    """
    data: PriceFunction_Data!
  ): PriceFunction_KeyOutput! @fdc_generated(from: "PriceFunction", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Product` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  product_insert(
    """
    Data object to insert into the table.
    """
    data: Product_Data!
  ): Product_KeyOutput! @fdc_generated(from: "Product", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ProductField` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  productField_insert(
    """
    Data object to insert into the table.
    """
    data: ProductField_Data!
  ): ProductField_KeyOutput! @fdc_generated(from: "ProductField", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Currencies` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  currencies_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Currencies_Data!]!
  ): [Currencies_KeyOutput!]! @fdc_generated(from: "Currencies", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PriceFunction` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  priceFunction_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PriceFunction_Data!]!
  ): [PriceFunction_KeyOutput!]! @fdc_generated(from: "PriceFunction", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Product` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  product_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Product_Data!]!
  ): [Product_KeyOutput!]! @fdc_generated(from: "Product", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ProductField` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  productField_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ProductField_Data!]!
  ): [ProductField_KeyOutput!]! @fdc_generated(from: "ProductField", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Currencies` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Currencies`.
  """
  currencies_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Currencies_Data!
  ): Currencies_KeyOutput! @fdc_generated(from: "Currencies", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PriceFunction` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PriceFunction`.
  """
  priceFunction_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PriceFunction_Data!
  ): PriceFunction_KeyOutput! @fdc_generated(from: "PriceFunction", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Product` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Product`.
  """
  product_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Product_Data!
  ): Product_KeyOutput! @fdc_generated(from: "Product", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ProductField` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProductField`.
  """
  productField_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ProductField_Data!
  ): ProductField_KeyOutput! @fdc_generated(from: "ProductField", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Currencies` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Currencies`.
  """
  currencies_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Currencies_Data!]!
  ): [Currencies_KeyOutput!]! @fdc_generated(from: "Currencies", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PriceFunction` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PriceFunction`.
  """
  priceFunction_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PriceFunction_Data!]!
  ): [PriceFunction_KeyOutput!]! @fdc_generated(from: "PriceFunction", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Product` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Product`.
  """
  product_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Product_Data!]!
  ): [Product_KeyOutput!]! @fdc_generated(from: "Product", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ProductField` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProductField`.
  """
  productField_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ProductField_Data!]!
  ): [ProductField_KeyOutput!]! @fdc_generated(from: "ProductField", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Currencies` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Currencies` or `null` if not found.
  """
  currencies_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Currencies_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Currencies_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Currencies_Data!
  ): Currencies_KeyOutput @fdc_generated(from: "Currencies", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PriceFunction` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PriceFunction` or `null` if not found.
  """
  priceFunction_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PriceFunction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PriceFunction_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PriceFunction_Data!
  ): PriceFunction_KeyOutput @fdc_generated(from: "PriceFunction", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Product` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Product` or `null` if not found.
  """
  product_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Product_Data!
  ): Product_KeyOutput @fdc_generated(from: "Product", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ProductField` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ProductField` or `null` if not found.
  """
  productField_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProductField_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductField_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ProductField_Data!
  ): ProductField_KeyOutput @fdc_generated(from: "ProductField", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Currencies` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  currencies_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Currencies_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Currencies_Data!
  ): Int! @fdc_generated(from: "Currencies", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PriceFunction` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  priceFunction_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PriceFunction_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PriceFunction_Data!
  ): Int! @fdc_generated(from: "PriceFunction", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Product` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  product_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Product_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Product_Data!
  ): Int! @fdc_generated(from: "Product", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ProductField` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  productField_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ProductField_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ProductField_Data!
  ): Int! @fdc_generated(from: "ProductField", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Currencies` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  currencies_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Currencies_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Currencies_FirstRow
  ): Currencies_KeyOutput @fdc_generated(from: "Currencies", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PriceFunction` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  priceFunction_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PriceFunction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PriceFunction_FirstRow
  ): PriceFunction_KeyOutput @fdc_generated(from: "PriceFunction", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Product` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  product_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow
  ): Product_KeyOutput @fdc_generated(from: "Product", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ProductField` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  productField_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProductField_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductField_FirstRow
  ): ProductField_KeyOutput @fdc_generated(from: "ProductField", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Currencies` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  currencies_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Currencies_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Currencies", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PriceFunction` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  priceFunction_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PriceFunction_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PriceFunction", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Product` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  product_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Product_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Product", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ProductField` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  productField_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ProductField_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ProductField", purpose: DELETE_MULTIPLE)
}
