extend type Mutation {
  """
  ✨ Insert a single `CartItem` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cartItem_insert(
    """
    Data object to insert into the table.
    """
    data: CartItem_Data!
  ): CartItem_KeyOutput! @fdc_generated(from: "CartItem", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Currencies` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  currencies_insert(
    """
    Data object to insert into the table.
    """
    data: Currencies_Data!
  ): Currencies_KeyOutput! @fdc_generated(from: "Currencies", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `FeaturedProduct` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  featuredProduct_insert(
    """
    Data object to insert into the table.
    """
    data: FeaturedProduct_Data!
  ): FeaturedProduct_KeyOutput! @fdc_generated(from: "FeaturedProduct", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Product` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  product_insert(
    """
    Data object to insert into the table.
    """
    data: Product_Data!
  ): Product_KeyOutput! @fdc_generated(from: "Product", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ProductField` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  productField_insert(
    """
    Data object to insert into the table.
    """
    data: ProductField_Data!
  ): ProductField_KeyOutput! @fdc_generated(from: "ProductField", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserPreference` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userPreference_insert(
    """
    Data object to insert into the table.
    """
    data: UserPreference_Data!
  ): UserPreference_KeyOutput! @fdc_generated(from: "UserPreference", purpose: INSERT_SINGLE)
  """
  ✨ Insert `CartItem` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cartItem_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CartItem_Data!]!
  ): [CartItem_KeyOutput!]! @fdc_generated(from: "CartItem", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Currencies` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  currencies_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Currencies_Data!]!
  ): [Currencies_KeyOutput!]! @fdc_generated(from: "Currencies", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `FeaturedProduct` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  featuredProduct_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [FeaturedProduct_Data!]!
  ): [FeaturedProduct_KeyOutput!]! @fdc_generated(from: "FeaturedProduct", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Product` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  product_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Product_Data!]!
  ): [Product_KeyOutput!]! @fdc_generated(from: "Product", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ProductField` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  productField_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ProductField_Data!]!
  ): [ProductField_KeyOutput!]! @fdc_generated(from: "ProductField", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserPreference` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userPreference_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserPreference_Data!]!
  ): [UserPreference_KeyOutput!]! @fdc_generated(from: "UserPreference", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `CartItem` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CartItem`.
  """
  cartItem_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CartItem_Data!
  ): CartItem_KeyOutput! @fdc_generated(from: "CartItem", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Currencies` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Currencies`.
  """
  currencies_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Currencies_Data!
  ): Currencies_KeyOutput! @fdc_generated(from: "Currencies", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `FeaturedProduct` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FeaturedProduct`.
  """
  featuredProduct_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: FeaturedProduct_Data!
  ): FeaturedProduct_KeyOutput! @fdc_generated(from: "FeaturedProduct", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Product` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Product`.
  """
  product_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Product_Data!
  ): Product_KeyOutput! @fdc_generated(from: "Product", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ProductField` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProductField`.
  """
  productField_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ProductField_Data!
  ): ProductField_KeyOutput! @fdc_generated(from: "ProductField", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserPreference` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserPreference`.
  """
  userPreference_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserPreference_Data!
  ): UserPreference_KeyOutput! @fdc_generated(from: "UserPreference", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `CartItem` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CartItem`.
  """
  cartItem_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CartItem_Data!]!
  ): [CartItem_KeyOutput!]! @fdc_generated(from: "CartItem", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Currencies` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Currencies`.
  """
  currencies_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Currencies_Data!]!
  ): [Currencies_KeyOutput!]! @fdc_generated(from: "Currencies", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `FeaturedProduct` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FeaturedProduct`.
  """
  featuredProduct_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [FeaturedProduct_Data!]!
  ): [FeaturedProduct_KeyOutput!]! @fdc_generated(from: "FeaturedProduct", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Product` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Product`.
  """
  product_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Product_Data!]!
  ): [Product_KeyOutput!]! @fdc_generated(from: "Product", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ProductField` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProductField`.
  """
  productField_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ProductField_Data!]!
  ): [ProductField_KeyOutput!]! @fdc_generated(from: "ProductField", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserPreference` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserPreference`.
  """
  userPreference_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserPreference_Data!]!
  ): [UserPreference_KeyOutput!]! @fdc_generated(from: "UserPreference", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `CartItem` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CartItem` or `null` if not found.
  """
  cartItem_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CartItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CartItem_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CartItem_Data!
  ): CartItem_KeyOutput @fdc_generated(from: "CartItem", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Currencies` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Currencies` or `null` if not found.
  """
  currencies_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Currencies_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Currencies_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Currencies_Data!
  ): Currencies_KeyOutput @fdc_generated(from: "Currencies", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `FeaturedProduct` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `FeaturedProduct` or `null` if not found.
  """
  featuredProduct_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FeaturedProduct_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FeaturedProduct_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: FeaturedProduct_Data!
  ): FeaturedProduct_KeyOutput @fdc_generated(from: "FeaturedProduct", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Product` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Product` or `null` if not found.
  """
  product_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Product_Data!
  ): Product_KeyOutput @fdc_generated(from: "Product", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ProductField` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ProductField` or `null` if not found.
  """
  productField_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProductField_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductField_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ProductField_Data!
  ): ProductField_KeyOutput @fdc_generated(from: "ProductField", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserPreference` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserPreference` or `null` if not found.
  """
  userPreference_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserPreference_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserPreference_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserPreference_Data!
  ): UserPreference_KeyOutput @fdc_generated(from: "UserPreference", purpose: UPDATE_SINGLE)
  """
  ✨ Update `CartItem` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  cartItem_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CartItem_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CartItem_Data!
  ): Int! @fdc_generated(from: "CartItem", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Currencies` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  currencies_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Currencies_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Currencies_Data!
  ): Int! @fdc_generated(from: "Currencies", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `FeaturedProduct` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  featuredProduct_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: FeaturedProduct_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: FeaturedProduct_Data!
  ): Int! @fdc_generated(from: "FeaturedProduct", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Product` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  product_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Product_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Product_Data!
  ): Int! @fdc_generated(from: "Product", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ProductField` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  productField_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ProductField_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ProductField_Data!
  ): Int! @fdc_generated(from: "ProductField", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserPreference` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userPreference_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserPreference_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserPreference_Data!
  ): Int! @fdc_generated(from: "UserPreference", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `CartItem` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  cartItem_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CartItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CartItem_FirstRow
  ): CartItem_KeyOutput @fdc_generated(from: "CartItem", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Currencies` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  currencies_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Currencies_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Currencies_FirstRow
  ): Currencies_KeyOutput @fdc_generated(from: "Currencies", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `FeaturedProduct` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  featuredProduct_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FeaturedProduct_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FeaturedProduct_FirstRow
  ): FeaturedProduct_KeyOutput @fdc_generated(from: "FeaturedProduct", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Product` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  product_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow
  ): Product_KeyOutput @fdc_generated(from: "Product", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ProductField` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  productField_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProductField_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductField_FirstRow
  ): ProductField_KeyOutput @fdc_generated(from: "ProductField", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserPreference` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userPreference_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserPreference_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserPreference_FirstRow
  ): UserPreference_KeyOutput @fdc_generated(from: "UserPreference", purpose: DELETE_SINGLE)
  """
  ✨ Delete `CartItem` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  cartItem_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CartItem_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CartItem", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Currencies` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  currencies_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Currencies_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Currencies", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `FeaturedProduct` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  featuredProduct_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: FeaturedProduct_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "FeaturedProduct", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Product` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  product_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Product_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Product", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ProductField` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  productField_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ProductField_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ProductField", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserPreference` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userPreference_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserPreference_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserPreference", purpose: DELETE_MULTIPLE)
}
