extend type Query {
  """
  ✨ Look up a single `CartItem` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  cartItem(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CartItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CartItem_FirstRow
  ): CartItem @fdc_generated(from: "CartItem", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Currencies` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  currencies(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Currencies_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Currencies_FirstRow
  ): Currencies @fdc_generated(from: "Currencies", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `FeaturedProduct` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  featuredProduct(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FeaturedProduct_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FeaturedProduct_FirstRow
  ): FeaturedProduct @fdc_generated(from: "FeaturedProduct", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Product` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  product(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow
  ): Product @fdc_generated(from: "Product", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ProductField` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  productField(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProductField_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductField_FirstRow
  ): ProductField @fdc_generated(from: "ProductField", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserPreference` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userPreference(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserPreference_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserPreference_FirstRow
  ): UserPreference @fdc_generated(from: "UserPreference", purpose: QUERY_SINGLE)
  """
  ✨ List `CartItem` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  cartItems(
    """
    Filter condition to narrow down the query results.
    """
    where: CartItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [CartItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: CartItem_Having
  ): [CartItem!]! @fdc_generated(from: "CartItem", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Currencies` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  currenciess(
    """
    Filter condition to narrow down the query results.
    """
    where: Currencies_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Currencies_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Currencies_Having
  ): [Currencies!]! @fdc_generated(from: "Currencies", purpose: QUERY_MULTIPLE)
  """
  ✨ List `FeaturedProduct` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  featuredProducts(
    """
    Filter condition to narrow down the query results.
    """
    where: FeaturedProduct_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FeaturedProduct_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FeaturedProduct_Having
  ): [FeaturedProduct!]! @fdc_generated(from: "FeaturedProduct", purpose: QUERY_MULTIPLE)
  """
  ✨ List `OfUserCartItemCounter` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  ofUserCartItemCounters(
    """
    Filter condition to narrow down the query results.
    """
    where: OfUserCartItemCounter_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [OfUserCartItemCounter_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: OfUserCartItemCounter_Having
  ): [OfUserCartItemCounter!]! @fdc_generated(from: "OfUserCartItemCounter", purpose: QUERY_MULTIPLE)
  """
  ✨ List `OfUserOfProductCartItemCounter` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  ofUserOfProductCartItemCounters(
    """
    Filter condition to narrow down the query results.
    """
    where: OfUserOfProductCartItemCounter_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [OfUserOfProductCartItemCounter_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: OfUserOfProductCartItemCounter_Having
  ): [OfUserOfProductCartItemCounter!]! @fdc_generated(from: "OfUserOfProductCartItemCounter", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Product` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  products(
    """
    Filter condition to narrow down the query results.
    """
    where: Product_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Product_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Product_Having
  ): [Product!]! @fdc_generated(from: "Product", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ProductField` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  productFields(
    """
    Filter condition to narrow down the query results.
    """
    where: ProductField_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ProductField_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ProductField_Having
  ): [ProductField!]! @fdc_generated(from: "ProductField", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserPreference` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userPreferences(
    """
    Filter condition to narrow down the query results.
    """
    where: UserPreference_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserPreference_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserPreference_Having
  ): [UserPreference!]! @fdc_generated(from: "UserPreference", purpose: QUERY_MULTIPLE)
}
