extend type CartItem {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "CartItem", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `CartItem` table.
  """
  _count: Int! @fdc_generated(from: "CartItem.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `checkoutPrice` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  checkoutPrice_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.checkoutPrice", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `comment` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  comment_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.comment", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `currency` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  currency_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.currency", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `productId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.productId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `productName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.productName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `purchaseData` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  purchaseData_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.purchaseData", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `statusChangedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  statusChangedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.statusChangedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `CartItem` table where the `userName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "CartItem.userName", purpose: QUERY_COUNT)
  """
  ✨ Sum the `checkoutPrice` field in the `CartItem` table.
  """
  checkoutPrice_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "CartItem.checkoutPrice", purpose: QUERY_SUM)
  """
  ✨ Average the `checkoutPrice` field in the `CartItem` table.
  """
  checkoutPrice_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "CartItem.checkoutPrice", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `checkoutPrice` field in the `CartItem` table.
  """
  checkoutPrice_min: Float @fdc_generated(from: "CartItem.checkoutPrice", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `CartItem` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "CartItem.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `purchaseData` field in the `CartItem` table.
  """
  purchaseData_min: Any @fdc_generated(from: "CartItem.purchaseData", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `statusChangedAt` field in the `CartItem` table.
  """
  statusChangedAt_min: Timestamp @fdc_generated(from: "CartItem.statusChangedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `checkoutPrice` field in the `CartItem` table.
  """
  checkoutPrice_max: Float @fdc_generated(from: "CartItem.checkoutPrice", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `CartItem` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "CartItem.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `purchaseData` field in the `CartItem` table.
  """
  purchaseData_max: Any @fdc_generated(from: "CartItem.purchaseData", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `statusChangedAt` field in the `CartItem` table.
  """
  statusChangedAt_max: Timestamp @fdc_generated(from: "CartItem.statusChangedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "CartItem.id", purpose: ENTITY_ID)
}
extend type Currencies {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Currencies", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Currencies` table.
  """
  _count: Int! @fdc_generated(from: "Currencies.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Currencies` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Currencies.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Currencies` table where the `mainCurrency` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  mainCurrency_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Currencies.mainCurrency", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Currencies` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Currencies.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Currencies` table where the `rub` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  rub_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Currencies.rub", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Currencies` table where the `usd` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  usd_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Currencies.usd", purpose: QUERY_COUNT)
  """
  ✨ Sum the `rub` field in the `Currencies` table.
  """
  rub_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Currencies.rub", purpose: QUERY_SUM)
  """
  ✨ Sum the `usd` field in the `Currencies` table.
  """
  usd_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Currencies.usd", purpose: QUERY_SUM)
  """
  ✨ Average the `rub` field in the `Currencies` table.
  """
  rub_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Currencies.rub", purpose: QUERY_AVG)
  """
  ✨ Average the `usd` field in the `Currencies` table.
  """
  usd_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Currencies.usd", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `rub` field in the `Currencies` table.
  """
  rub_min: Float @fdc_generated(from: "Currencies.rub", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `usd` field in the `Currencies` table.
  """
  usd_min: Float @fdc_generated(from: "Currencies.usd", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `rub` field in the `Currencies` table.
  """
  rub_max: Float @fdc_generated(from: "Currencies.rub", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `usd` field in the `Currencies` table.
  """
  usd_max: Float @fdc_generated(from: "Currencies.usd", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Currencies.id", purpose: ENTITY_ID)
}
extend type OfUserCartItemCounter {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "OfUserCartItemCounter", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `OfUserCartItemCounter` table.
  """
  _count: Int! @fdc_generated(from: "OfUserCartItemCounter.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OfUserCartItemCounter` table where the `userCartItemCount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userCartItemCount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OfUserCartItemCounter.userCartItemCount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OfUserCartItemCounter` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OfUserCartItemCounter.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `userCartItemCount` field in the `OfUserCartItemCounter` table.
  """
  userCartItemCount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "OfUserCartItemCounter.userCartItemCount", purpose: QUERY_SUM)
  """
  ✨ Average the `userCartItemCount` field in the `OfUserCartItemCounter` table.
  """
  userCartItemCount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OfUserCartItemCounter.userCartItemCount", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `userCartItemCount` field in the `OfUserCartItemCounter` table.
  """
  userCartItemCount_min: Int @fdc_generated(from: "OfUserCartItemCounter.userCartItemCount", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `userCartItemCount` field in the `OfUserCartItemCounter` table.
  """
  userCartItemCount_max: Int @fdc_generated(from: "OfUserCartItemCounter.userCartItemCount", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "OfUserCartItemCounter", purpose: ENTITY_ID)
}
extend type OfUserOfProductCartItemCounter {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "OfUserOfProductCartItemCounter", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `OfUserOfProductCartItemCounter` table.
  """
  _count: Int! @fdc_generated(from: "OfUserOfProductCartItemCounter.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OfUserOfProductCartItemCounter` table where the `productCartItemCount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productCartItemCount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OfUserOfProductCartItemCounter.productCartItemCount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OfUserOfProductCartItemCounter` table where the `productId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OfUserOfProductCartItemCounter.productId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OfUserOfProductCartItemCounter` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OfUserOfProductCartItemCounter.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `productCartItemCount` field in the `OfUserOfProductCartItemCounter` table.
  """
  productCartItemCount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "OfUserOfProductCartItemCounter.productCartItemCount", purpose: QUERY_SUM)
  """
  ✨ Average the `productCartItemCount` field in the `OfUserOfProductCartItemCounter` table.
  """
  productCartItemCount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OfUserOfProductCartItemCounter.productCartItemCount", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `productCartItemCount` field in the `OfUserOfProductCartItemCounter` table.
  """
  productCartItemCount_min: Int @fdc_generated(from: "OfUserOfProductCartItemCounter.productCartItemCount", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `productCartItemCount` field in the `OfUserOfProductCartItemCounter` table.
  """
  productCartItemCount_max: Int @fdc_generated(from: "OfUserOfProductCartItemCounter.productCartItemCount", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "OfUserOfProductCartItemCounter", purpose: ENTITY_ID)
}
extend type Product {
  """
  ✨ List `ProductField` objects in a one-to-many relationship (where `ProductField`.`product` is this object).
  """
  productFields_on_product(
    """
    Filter condition to narrow down the query results.
    """
    where: ProductField_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ProductField_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ProductField_Having
  ): [ProductField!]! @fdc_generated(from: "ProductField.product", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Product", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Product` table.
  """
  _count: Int! @fdc_generated(from: "Product.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `currencies` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  currencies_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.currencies", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.name", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Product.id", purpose: ENTITY_ID)
}
extend type ProductField {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ProductField", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ProductField` table.
  """
  _count: Int! @fdc_generated(from: "ProductField.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductField` table where the `fieldName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fieldName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductField.fieldName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductField` table where the `handler` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  handler_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductField.handler", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductField` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductField.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductField` table where the `isPriceImage` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isPriceImage_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductField.isPriceImage", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductField` table where the `order` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  order_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductField.order", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductField` table where the `priceImages` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  priceImages_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductField.priceImages", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductField` table where the `productId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductField.productId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `order` field in the `ProductField` table.
  """
  order_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "ProductField.order", purpose: QUERY_SUM)
  """
  ✨ Average the `order` field in the `ProductField` table.
  """
  order_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "ProductField.order", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `order` field in the `ProductField` table.
  """
  order_min: Int @fdc_generated(from: "ProductField.order", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `priceImages` field in the `ProductField` table.
  """
  priceImages_min: Any @fdc_generated(from: "ProductField.priceImages", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `order` field in the `ProductField` table.
  """
  order_max: Int @fdc_generated(from: "ProductField.order", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `priceImages` field in the `ProductField` table.
  """
  priceImages_max: Any @fdc_generated(from: "ProductField.priceImages", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ProductField.id", purpose: ENTITY_ID)
}
