type Product @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  name: String!
  description: String!
  imageUrl: String!
  currencies: String!
}

type ProductField @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  product: Product!
  order: Int!
  fieldName: String!
  isPriceImage: Boolean! @default(value: false)
  handler: String!
  attributes: Any
  expectedData: [String!] # which fields will return an information
}

type Currencies @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  name: String!
  mainCurrency: String!
  rub: Float!
  usd: Float!
}
